### ISSUE TITLE
Deep Github intergration - Releases

### ISSUE THREAD

**Issue by alrik** [release-notes/release-notes-hub#41]
As a software maintainer I want to create and sync a release-notes page with github releases.

Relates to #40 

**ToDo**:

* [ ] Research if github provides webhooks for release update events

**Acceptance Criteria**:

* [ ] There is a new option to sync a release-notes page with "github releases"

**Nice to Have**:

* [ ] Create release-notes.yml or CHANGELOG.md from github releases
